FROM python:3.10.12

WORKDIR /app

COPY domain-chatbot .

RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    rm -rf ~/.cache/pip && \
    rm -rf /tmp/* && \
    mkdir -p tmp media logs db && \
    python manage.py makemigrations && \
    python manage.py migrate

ENV OPENAI_API_KEY=sk-xxxxx
ENV B_STATION_ID=xxxx
ENV B_UID=12xx
ENV TIMEZONE=Asia/Shanghai

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]