# Generated by Django 4.2.1 on 2026-04-10 00:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='face_recognition_app.learningsession')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_expression', models.CharField(max_length=20)),
                ('suggested_topic', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', '待触发'), ('triggered', '已触发'), ('dismissed', '已忽略')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='face_recognition_app.learningsession')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(choices=[('happy', '开心'), ('sad', '悲伤'), ('angry', '愤怒'), ('surprised', '惊讶'), ('neutral', '中性'), ('confused', '困惑'), ('bored', '无聊'), ('focused', '专注')], max_length=20)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('frame_data', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='face_recognition_app.learningsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
